Fix service failure in vmware
Tendrl/node-agent pull request #881
Opened 2020-05-13 15:38 UTC by TimothyAsirJeyasing

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

2020-05-13 15:39 UTC, TimothyAsirJeyasing commented
@aruniiird , @GowthamShanmugam , @shtripat Please review

2020-05-29 12:15 UTC, TimothyAsirJeyasing commented
@aruniiird , @GowthamShanmugam , @shtripat Please review

2020-05-29 12:55 UTC, aruniiird requested changes
A minor change request.

2020-05-29 12:55 UTC, aruniiird commented on tendrl/node_agent/node_sync/disk_sync.py
> +                    devlist["device"] + "_" + devlist["hardware_id"])
```suggestion
                 devlist["disk_id"] = "{vendor}_{device}_{hardware_id}".format(**devlist)
```
makes it much efficient than the `+` concatenation.

2020-05-29 12:57 UTC, aruniiird reviewed
We are generally ignoring the errors (referring to the unicode conversion part), is that fine?

2020-06-04 15:33 UTC, aruniiird commented on tendrl/node_agent/node_sync/disk_sync.py
> +                    "{vendor}_{device}_{parent_id}{hardware_id}".format(**devlist)
```suggestion
                    "{vendor}_{device}_{parent_id}_{hardware_id}".format(**devlist)
```

2020-06-05 11:52 UTC, aruniiird commented
/lgtm

2020-06-05 11:56 UTC, aruniiird approved these changes

2020-06-05 11:57 UTC, merged